# Generated by Django 4.2.3 on 2023-07-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fake_accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('creationDate', models.DateTimeField()),
                ('accountEmail', models.EmailField(max_length=254)),
                ('accountID', models.UUIDField()),
                ('fake_ccNumber', models.DateTimeField(auto_now_add=True)),
                ('fake_ccIssuer', models.CharField(max_length=64)),
                ('fake_ethereumAddress', models.CharField(max_length=128)),
                ('fake_currencyName', models.CharField(max_length=128)),
                ('fake_currencyCode', models.CharField(max_length=10)),
            ],
        ),
    ]
