# Generated by Django 4.2.3 on 2023-07-07 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_memes_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fake_accounts',
            name='accountID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='fake_accounts',
            name='creationDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
